export default [
  //系统设置
  {
    path: "/system",
    name: "system",
    component: 'Main',
    meta: {
      title: "系统设置",
      icon: "ios-keypad",
      access: ["/system"],
    },
    children: [
      {
        path: "/system/role",
        meta: {
          icon: "ios-browsers",
          title: "角色管理",
          sidehead: "角色管理-后台管理系统",
          access: ["view/system/role-list.html"],
        },
        name: "system_role",
        component: "view/system/role",
      },
      {
        path: "/role/detail",
        name: "role_detail",
        meta: {
          icon: "ios-browsers",
          title: "角色编辑",
          sidehead: "角色编辑-后台管理系统",
          hideInMenu: true,
        },
        component: "view/system/role/detail",
      },
      {
        path: "/system/admUser",
        meta: {
          icon: "ios-browsers",
          title: "账号管理",
          sidehead: "账号管理-后台管理系统",
          access: ["view/system/account-list.html"],
          keepAlive: true,
        },
        name: "system_admUser",
        component: "view/system/adm-user",
      },
      {
        path: "/system/menu-management",
        meta: {
          icon: "ios-browsers",
          title: "菜单管理",
          sidehead: "菜单管理-后台管理系统",
          // access: ["view/system/menu-management.html"],
          keepAlive: true,
        },
        name: "menu-management",
        // component: "view/system/menu-management/index"),
        component: "view/system/menu-management",
      },
      {
        path: "/admUser/detail",
        name: "admUser_detail",
        meta: {
          icon: "ios-browsers",
          title: "账号编辑",
          sidehead: "账号编辑-后台管理系统",
          hideInMenu: true,
        },
        component: "view/system/adm-user/detail",
      },
      {
        path: "/system/pwd_reset",
        meta: {
          icon: "ios-browsers",
          title: "密码修改",
          sidehead: "密码修改-后台管理系统",
          // access: ['/user/updateLoginPwd']
        },
        name: "system_pwd_reset",
        component: "view/system/pwd-reset",
      },
      {
        path: "/system/sms_reset",
        meta: {
          icon: "ios-browsers",
          title: "短信设置",
          sidehead: "短信设置-后台管理系统",
          access: ["dd488ed8-8b61-47cc-a5be-ae943fe51787"],
        },
        name: "system_sms_reset",
        component: "view/system/sms-reset",
      },
      {
        path: "/system/application",
        meta: { icon: "ios-browsers", title: "应用设置", sidehead: "应用设置-后台管理系统", access: ["view/system/app-list.html"] },
        name: "system_application",
        component: "view/system/application",
      },
      {
        path: "/application/detail",
        name: "application_detail",
        meta: {
          icon: "ios-browsers",
          title: "应用编辑",
          sidehead: "应用编辑-后台管理系统",
          hideInMenu: true,
        },
        component: "view/system/application/detail",
      },
      {
        path: "/system/app_update",
        meta: {
          icon: "ios-browsers",
          title: "APP更新",
          sidehead: "APP更新-后台管理系统",
          access: ["view/app/update-list.html"],
        },
        name: "system_app_update",
        component: "view/system/app-update",
      },
      {
        path: "/app_update/detail",
        name: "app_update_detail",
        meta: {
          icon: "ios-browsers",
          title: "APP升级",
          sidehead: "APP升级-后台管理系统",
          hideInMenu: true,
        },
        component: "view/system/app-update/detail",
      },
      {
        path: "/app_update/update_log",
        name: "app_update_update_log",
        meta: {
          icon: "ios-browsers",
          title: "APP升级记录",
          sidehead: "APP升级记录-后台管理系统",
          hideInMenu: true,
        },
        component: "view/system/app-update/update-log",
      },
      {
        path: "/system/app_audit",
        meta: {
          icon: "ios-browsers",
          title: "渠道过审",
          sidehead: "过审设置-后台管理系统",
          access: ["view/system/audit-list.html"],
        },
        name: "system_app_audit",
        component: "view/system/audit",
      },
      {
        path: "/system/app_audit/account_number",
        meta: {
          icon: "ios-browsers",
          title: "测试账号过审",
          sidehead: "测试账号过审-后台管理系统",
          access: ["view/system/audit-list/account_number.html"],
        },
        name: "system_app_audit/account_number",
        component: "view/system/audit/account-number.vue",
      },
      {
        path: "/system/app_audit/ip",
        meta: {
          icon: "ios-browsers",
          title: "IP过审",
          sidehead: "IP过审-后台管理系统",
          access: ["view/system/audit-list/ip.html"],
        },
        name: "system_app_audit/ip",
        component: "view/system/audit/ip.vue",
      },
      {
        path: "/system/certify_item",
        meta: {
          icon: "ios-browsers",
          title: "认证项管理",
          sidehead: "认证项管理-后台管理系统",
          access: [" view/certify/certify-item-list.html"],
          keepAlive: true,
        },
        name: "system_certify_item",
        component: "view/system/certify-item",
      },
      // h5域名配置
      {
        path: "/system/h5_domain",
        meta: {
          icon: "ios-browsers",
          title: "h5域名配置",
          sidehead: "h5域名配置-后台管理系统",
          access: ["/system/h5_domain"],
        },
        name: "system_h5_domain",
        component: "view/system/h5_domain",
      },
      {
        path: "business-setting",
        name: "business-setting",
        meta: {
          icon: "md-list",
          title: "机构审核配置",
          sidehead: "机构审核配置-后台管理系统",
          access: ["view/business/business-setting-new-credit.html"],
        },
        component: "view/system/institutional_audit",
      },
    ],
  },
  //用户管理
  {
    path: "/member",
    name: "member",
    component: 'Main',
    meta: {
      title: "用户管理",
      icon: "md-contacts",
      access: ["/member-manage"],
    },
    children: [
      {
        path: "/member/manager",
        meta: { icon: "ios-browsers", title: "用户管理", keepAlive: true, sidehead: "用户管理-后台管理系统", access: ["view/member/member-list.html"] },
        name: "member_manager",
        component: "view/member/manager",
      },
      {
        path: "/member/manager/detail",
        meta: { icon: "ios-browsers", title: "用户详情", sidehead: "用户信息详情-后台管理系统", hideInMenu: true },
        name: "member_manager_detail",
        component: "view/member/manager/detail",
      },
      {
        path: "/member/amount",
        meta: { icon: "ios-browsers", title: "额度管理", keepAlive: true, sidehead: "额度管理-后台管理系统", access: ["view/member/amount-list.html"] },
        name: "member_amount",
        component: "view/member/amount",
      },
      {
        path: "account",
        meta: { icon: "ios-person", title: "金币管理", keepAlive: true, sidehead: "金币管理-后台管理系统", access: ["/account/list"] },
        name: "coin_account_list",
        component: "view/coin-manage/account",
      },
      {
        path: "account/detail",
        name: "coin_account_list_detail",
        meta: {
          icon: "ios-browsers",
          title: "金币记录",
          sidehead: "金币记录-后台管理系统",
          hideInMenu: true,
        },
        component: "view/coin-manage/account/detail",
      },
    ],
  },
  //服务管理
  {
    path: "/service",
    name: "service",
    component: 'Main',
    meta: {
      title: "服务管理",
      icon: "ios-cog",
      access: ["/serveProduct"],
    },
    children: [
      {
        path: "product-recommend",
        meta: {
          icon: "ios-pricetag",
          title: "产品推荐服务配置",
          sidehead: "产品推荐服务配置-后台管理系统",
          access: ["/serveProduct/priceList/{serveCode}"],
        },
        name: "service_product-recommend",
        component: "view/service/product-recommend",
      },
    ],
  },
  //内容管理
  {
    path: "/content",
    name: "content",
    component: 'Main',
    meta: {
      title: "内容管理",
      icon: "ios-cog",
      access: ["/content"],
    },
    children: [
      {
        path: "/content/product-thematic",
        meta: {
          icon: "ios-browsers",
          title: "产品专题",
          sidehead: "产品专题-后台管理系统",
          access: ["view/source/source-subject.html"],
          keepAlive: true,
        },
        name: "content_product_thematic",
        component: "view/content/product-thematic",
      },
      {
        path: "/content/product-thematic/detail",
        meta: {
          icon: "ios-browsers",
          title: "产品专题编辑",
          sidehead: "产品专题编辑-后台管理系统",
          access: ["/content/product-thematic/detail"],
        },
        name: "content_product_thematic_detail",
        component: "view/content/product-thematic/detail",
      },
      {
        path: "/content/article/list",
        meta: { icon: "ios-browsers", title: "资讯列表", keepAlive: true, sidehead: "资讯列表-后台管理系统", access: ["/information/list"] },
        name: "content_article_list",
        component: "view/content/article/list",
      },
      {
        path: "/content/article/list/detail",
        meta: {
          icon: "ios-browsers",
          title: "资讯列表详情",
          sidehead: "资讯列表详情-资讯列表-后台管理系统" /*access: ['/system/application']*/,
          hideInMenu: true,
        },
        name: "content_article_list_detail",
        component: "view/content/article/list/detail",
      },
      {
        path: "/content/article/material",
        meta: { icon: "ios-browsers", title: "资讯素材", keepAlive: true, sidehead: "资讯素材-后台管理系统", access: ["/information/list"] },
        name: "content_article_material",
        component: "view/content/article/material",
      },
      {
        path: "/content/article/type",
        meta: { icon: "ios-browsers", title: "资讯类型", sidehead: "资讯管理-后台管理系统", access: ["/information/type"] },
        name: "content_article_type",
        component: "view/content/article/type",
      },
      /*{
        path: '/content/loan-recommend',
        meta: {icon: 'ios-browsers', title: '银行贷推荐卡片', sidehead: '银行贷推荐卡片\t-后台管理系统', access: ['view/app-home/credit-recommend.html']},
        name: 'content_loan_recommend',
        component: () => import('@/view/content/loan-recommend')
      },*/
      {
        path: "complaint-list",
        meta: { icon: "md-list", title: "投诉管理", keepAlive: true, sidehead: "投诉管理-后台管理系统", access: ["view/complain/complain-list.html"] },
        name: "complaint_list",
        component: "view/complaint/list",
      },
    ],
  },
  // 广告素材管理
  {
    path: "/advertis-manage",
    name: "advertis_manage",
    component: 'Main',
    meta: {
      title: "广告素材管理",
      icon: "ios-cog",
      access: ["/advertis_manage"],
    },
    children: [
      {
        path: "/advertis-manage/pop",
        meta: { icon: "ios-pricetag", title: "弹窗广告", keepAlive: true, sidehead: "弹窗广告-后台管理系统", access: ["view/ad/pop-list.html"] },
        name: "advertis-manage-pop",
        component: "view/advertis-manage/pop",
      },
      {
        path: "/advertis-manage/pop/detail",
        meta: { icon: "ios-pricetag", title: "弹窗广告编辑", sidehead: "弹窗广告详情-后台管理系统", hideInMenu: true },
        name: "advertis-manage-pop-detail",
        component: "view/advertis-manage/pop/detail",
      },
      {
        path: "/advertis-manage/splash",
        meta: { icon: "ios-pricetag", title: "闪屏广告", keepAlive: true, sidehead: "闪屏广告-后台管理系统", access: ["view/ad/splash-list.html"] },
        name: "advertis-manage-splash",
        component: "view/advertis-manage/splash",
      },
      {
        path: "/advertis-manage/splash/detail",
        meta: { icon: "ios-pricetag", title: "闪屏广告编辑", sidehead: "闪屏广告编辑-后台管理系统", hideInMenu: true },
        name: "advertis-manage-splash_detail",
        component: "view/advertis-manage/splash/detail",
      },
      {
        path: "/advertis-manage/float",
        meta: { icon: "ios-pricetag", title: "悬浮广告", keepAlive: true, sidehead: "悬浮广告-后台管理系统", access: ["view/ad/float-list.html"] },
        name: "advertis-manage-float",
        component: "view/advertis-manage/float",
      },
      {
        path: "/advertis-manage/float/detail",
        meta: { icon: "ios-pricetag", title: "悬浮广告编辑", sidehead: "悬浮广告编辑-后台管理系统", hideInMenu: true },
        name: "advertis-manage-float-detail",
        component: "view/advertis-manage/float/detail",
      },
      {
        path: "/advertis-manage/suggest-ads",
        meta: {
          icon: "ios-browsers",
          title: "极速贷推荐卡片",
          sidehead: "极速贷推荐卡片-后台管理系统",
          access: ["/material/card/product-sp-recommend/detail"],
        },
        name: "advertis-manage-suggest-ads",
        component: "view/advertis-manage/suggest-ads",
      },
      {
        path: "/advertis-manage/pop-window",
        meta: {
          icon: "ios-browsers",
          title: "下拉弹窗推荐卡片",
          sidehead: "下拉弹窗推荐卡片-后台管理系统",
          access: ["/material/card/product-pop-windows/detail"],
        },
        name: "advertis-manage-pop-window",
        component: "view/advertis-manage/pop-window",
      },
      {
        path: "/advertis-manage/loan-recommend",
        meta: { icon: "ios-browsers", title: "银行贷推荐卡片", sidehead: "银行贷推荐卡片-后台管理系统", access: ["/material/card/bank-loan/detail"] },
        name: "advertis-manage-loan-recommend",
        component: "view/advertis-manage/loan-recommend",
      },
      {
        path: "/cash-loan-card",
        meta: {
          icon: "ios-browsers",
          title: "现金贷卡片",
          sidehead: "现金贷卡片-后台管理系统",
          access: ["/material/card/cash-loan/detail"],
        },
        name: "cash_loan_card",
        component: "view/content/cash-loan-card",
      },
      {
        path: "/advertis-manage/loan-product",
        meta: {
          icon: "ios-browsers",
          title: "银行贷精选产品",
          sidehead: "银行贷精选产品-后台管理系统",
          access: ["/material/card/bank-loan-choice/detail"],
        },
        name: "advertis-manage-loan-product",
        component: "view/advertis-manage/loan-product",
      },
      {
        path: "/advertis-manage/speed-product",
        meta: {
          icon: "ios-browsers",
          title: "极速贷精选产品",
          sidehead: "极速贷精选产品-后台管理系统",
          access: ["/material/card/speed-loan-choice/detail"],
        },
        name: "advertis-manage-speed-product",
        component: "view/advertis-manage/speed-product",
      },
      {
        path: "/advertis-manage/card-manger",
        meta: { icon: "ios-browsers", title: "产品入口卡片", sidehead: "产品入口卡片-后台管理系统", access: ["/material/card/entrance/detail"] },
        name: "advertis-manage-card-manger",
        component: "view/advertis-manage/card-manger",
      },
      {
        path: "/advertis-manage/card-recommend-manger",
        meta: {
          icon: "ios-browsers",
          title: "产品推荐卡片",
          sidehead: "产品推荐卡片-后台管理系统",
          access: ["7eafa836-26e9-4164-a34c-7175eefb7ade"],
        },
        name: "advertis-manage-card-recommend-manger",
        component: "view/advertis-manage/card-recommend-manger",
      },
      {
        path: "/advertis-manage/extend",
        meta: { icon: "ios-browsers", title: "栏目图标", keepAlive: true, sidehead: "栏目图标-后台管理系统", access: ["/advertis-manage/extend"] },
        name: "advertis-manage-extend",

        component: "view/advertis-manage/extend",
      },
      {
        path: "/advertis-manage/extend/extend-detail",
        meta: { icon: "ios-browsers", title: "图标详情", sidehead: "图标编辑-后台管理系统", hideInMenu: true, access: ["/material/card/nav/detail"] },
        name: "advertis-manage-extend-detail",

        component: "view/advertis-manage/extend/extend-detail",
      },
      {
        path: "/advertis-manage/extend/extend-edit",
        meta: { icon: "ios-browsers", title: "图标编辑", sidehead: "图标详情-后台管理系统", hideInMenu: true, access: ["/material/card/nav/save"] },
        name: "advertis-manage-extend-edit",

        component: "view/advertis-manage/extend/extend-edit",
      },
      {
        path: "/advertis-manage/personal-center",
        meta: { icon: "ios-pricetag", title: "个人中心广告", keepAlive: true, sidehead: "个人中心配置-后台管理系统", access: ["/advertis-manage/personal-center"] },
        name: "advertis-manage-personal-center",

        component: "view/advertis-manage/personal-center",
      },
      {
        path: "/advertis-manage/personal-center/personal-center-detail",
        meta: {
          icon: "ios-browsers",
          title: "图标详情",
          sidehead: "图标详情-后台管理系统",
          hideInMenu: true,
          access: ["/material/card/personalCenter/detail"],
        },
        name: "advertis-manage-personal-center-detail",

        component: "view/advertis-manage/personal-center/personal-center-detail",
      },
      {
        path: "/advertis-manage/personal-center/personal-center-edit",
        meta: {
          icon: "ios-browsers",
          title: "图标编辑",
          sidehead: "图标编辑-后台管理系统",
          hideInMenu: true,
          access: ["/material/card/personalCenter/save"],
        },
        name: "advertis-manage-personal-center-edit",

        component: "view/advertis-manage/personal-center/personal-center-edit",
      },
      {
        path: "/advertis-manage/copywriting",
        meta: { icon: "ios-paper", title: "文案素材", keepAlive: true, sidehead: "文案素材-后台管理系统", access: ["/advertis-manage/copywriting"] },
        name: "advertis-manage-copywriting",

        component: "view/advertis-manage/copywriting-material",
      },
      {
        path: "/advertis-manage/copywriting/edit",
        meta: {
          icon: "ios-paper",
          title: "文案素材编辑",
          sidehead: "文案素材编辑-后台管理系统",
          hideInMenu: true,
          access: ["/material/card/text/save"],
        },
        name: "advertis-manage-copywriting-edit",

        component: "view/advertis-manage/copywriting-material/edit",
      },
      {
        path: "/advertis-manage/copywriting/detail",
        meta: {
          icon: "ios-paper",
          title: "文案素材详情",
          sidehead: "文案素材详情-后台管理系统",
          hideInMenu: true,
          access: ["/material/card/text/detail"],
        },
        name: "advertis-manage-copywriting-detail",

        component: "view/advertis-manage/copywriting-material/detail",
      },
      {
        path: "/advertis-manage/loan-assistance",
        meta: { icon: "ios-browsers", title: "助贷咨询广告", keepAlive: true, sidehead: "助贷咨询广告-后台管理系统", access: ["/advertis-manage/loan-assistance"] },
        name: "advertis-manage-loan-assistance",

        component: "view/advertis-manage/loan-assistance",
      },
      {
        path: "/advertis-manage/loan-assistance/detail",
        meta: {
          icon: "ios-browsers",
          title: "助贷咨询广告详情",
          sidehead: "助贷咨询广告详情-后台管理系统",
          hideInMenu: true,
          access: ["/material/card/loanAssistance/detail"],
        },
        name: "advertis-manage-loan-assistance-detail",

        component: "view/advertis-manage/loan-assistance/detail",
      },
      {
        path: "/advertis-manage/loan-assistance/edit",
        meta: {
          icon: "ios-browsers",
          title: "助贷咨询广告编辑",
          sidehead: "助贷咨询广告编辑-后台管理系统",
          hideInMenu: true,
          access: ["/material/card/loanAssistance/save"],
        },
        name: "advertis-manage-loan-assistance-edit",

        component: "view/advertis-manage/loan-assistance/edit",
      },
      {
        path: "/advertis-manage/broadcast-material",
        meta: { icon: "ios-browsers", title: "广播素材", keepAlive: true, sidehead: "广播素材-后台管理系统" },
        name: "advertis-manage-broadcast-material",
        access: ["/advertis-manage/broadcast-material"],
        component: "view/advertis-manage/broadcast-material",
      },
      {
        path: "/advertis-manage/broadcast-material/detail",
        meta: {
          icon: "ios-browsers",
          title: "广播素材详情",
          sidehead: "图标编辑-后台管理系统",
          hideInMenu: true,
          access: ["/material/card/broadcastMaterial/detail"],
        },
        name: "advertis-manage-broadcast-material-detail",

        component: "view/advertis-manage/broadcast-material/detail",
      },
      {
        path: "/advertis-manage/broadcast-material/edit",
        meta: {
          icon: "ios-browsers",
          title: "广播素材编辑",
          sidehead: "图标详情-后台管理系统",
          hideInMenu: true,
          access: ["/material/card/broadcastMaterial/save"],
        },
        name: "advertis-manage-broadcast-material-edit",

        component: "view/advertis-manage/broadcast-material/edit",
      },
      {
        path: "/advertis-manage/notice",
        meta: { icon: "ios-browsers", title: "通知素材", keepAlive: true, sidehead: "通知素材-后台管理系统" },
        name: "advertis-manage-notice",
        access: ["/advertis-manage/notice"],
        component: "view/advertis-manage/notice",
      },
      {
        path: "/advertis-manage/notice/detail",
        meta: {
          icon: "ios-browsers",
          title: "通知素材详情",
          sidehead: "通知素材详情-后台管理系统",
          hideInMenu: true,
          access: ["/material/card/notice/detail"],
        },
        name: "advertis-manage-notice-detail",

        component: "view/advertis-manage/notice/detail",
      },
      {
        path: "/advertis-manage/notice/edit",
        meta: {
          icon: "ios-browsers",
          title: "通知素材编辑",
          sidehead: "通知素材编辑-后台管理系统",
          hideInMenu: true,
          access: ["/material/card/notice/save"],
        },
        name: "advertis-manage-notice-edit",

        component: "view/advertis-manage/notice/edit",
      },
      {
        path: "/advertis-manage/marketplace",
        meta: { icon: "ios-browsers", title: "商城卡片", keepAlive: true, sidehead: "商城卡片-后台管理系统" },
        name: "advertis-manage-marketplace",
        access: ["/advertis-manage/marketplace"],
        component: "view/advertis-manage/marketplace",
      },
      {
        path: "/advertis-manage/marketplace/detail",
        meta: {
          icon: "ios-browsers",
          title: "商城卡片详情",
          sidehead: "商城卡片详情-后台管理系统",
          hideInMenu: true,
          access: ["/material/card/broadCastMaterial/detail"],
        },
        name: "advertis-manage-marketplace-detail",

        component: "view/advertis-manage/marketplace/detail",
      },
      {
        path: "/advertis-manage/marketplace/edit",
        meta: {
          icon: "ios-browsers",
          title: "商城卡片编辑",
          sidehead: "商城卡片编辑-后台管理系统",
          hideInMenu: true,
          access: ["/material/card/marketplace/save"],
        },
        name: "advertis-manage-marketplace-edit",

        component: "view/advertis-manage/marketplace/edit",
      },
      {
        path: "/advertis-manage/three-picture-card",
        meta: {
          icon: "ios-browsers",
          title: "三图卡片",
          sidehead: "三图卡片-广告素材管理-后台管理系统",
          access: ["/material/card/multiple-picture/list"],
          keepAlive: true,
        },
        name: "three-picture-card",
        component: "view/advertis-manage/three-picture-card",
      },
      {
        path: "/advertis-manage/three-picture-card/detail",
        meta: {
          icon: "ios-browsers",
          title: "三图卡片详情",
          sidehead: "三图卡片详情-广告素材管理-后台管理系统",
          hideInMenu: true,
          access: ["/material/card/multiple-picture/detail"],
        },
        name: "three-picture-card-detail",
        component: "view/advertis-manage/three-picture-card/detail",
      },
      {
        path: "/advertis-manage/three-picture-card/edit",
        meta: {
          icon: "ios-browsers",
          title: "三图卡片编辑",
          sidehead: "三图卡片编辑-广告素材管理-后台管理系统",
          hideInMenu: true,
          access: ["/material/card/multiple-picture/save"],
        },
        name: "three-picture-card-edit",
        component: "view/advertis-manage/three-picture-card/edit",
      },
      {
        path: "/advertis-manage/double-row-one",
        meta: {
          icon: "ios-browsers",
          title: "双列多行样式一",
          sidehead: "双列多行样式一-广告素材管理-后台管理系统",
          access: ["/material/card/multiple-picture/list"],
          keepAlive: true,
        },
        name: "double-row-one",
        component: "view/advertis-manage/double-row-one",
      },
      {
        path: "/advertis-manage/double-row-one/detail",
        meta: {
          icon: "ios-browsers",
          title: "双列多行样式一详情",
          sidehead: "双列多行样式一详情-广告素材管理-后台管理系统",
          hideInMenu: true,
          access: ["/material/card/multiple-picture/detail"],
        },
        name: "double-row-one-detail",
        component: "view/advertis-manage/double-row-one/detail",
      },
      {
        path: "/advertis-manage/double-row-one/edit",
        meta: {
          icon: "ios-browsers",
          title: "双列多行样式一编辑",
          sidehead: "双列多行样式一编辑-广告素材管理-后台管理系统",
          hideInMenu: true,
          access: ["/material/card/multiple-picture/save"],
        },
        name: "double-row-one-edit",
        component: "view/advertis-manage/double-row-one/edit",
      },
      {
        path: "/advertis-manage/double-row-two",
        meta: {
          icon: "ios-browsers",
          title: "双列多行样式二",
          sidehead: "双列多行样式二-广告素材管理-后台管理系统",
          access: ["/material/card/multiple-picture/list"],
          keepAlive: true,
        },
        name: "double-row-two",
        component: "view/advertis-manage/double-row-two",
      },
      {
        path: "/advertis-manage/double-row-two/detail",
        meta: {
          icon: "ios-browsers",
          title: "双列多行样式二详情",
          sidehead: "双列多行样式二详情-广告素材管理-后台管理系统",
          hideInMenu: true,
          access: ["/material/card/multiple-picture/detail"],
        },
        name: "double-row-two-detail",
        component: "view/advertis-manage/double-row-two/detail",
      },
      {
        path: "/advertis-manage/double-row-two/edit",
        meta: {
          icon: "ios-browsers",
          title: "双列多行样式二编辑",
          sidehead: "双列多行样式二编辑-广告素材管理-后台管理系统",
          hideInMenu: true,
          access: ["/material/card/multiple-picture/save"],
        },
        name: "double-row-two-edit",
        component: "view/advertis-manage/double-row-two/edit",
      },
      {
        path: "/advertis-manage/popular-information",
        meta: {
          icon: "ios-browsers",
          title: "热门资讯",
          sidehead: "热门资讯-广告素材管理-后台管理系统",
          access: ["/material/card/article/list"],
          keepAlive: true,
        },
        name: "popular-information",
        component: "view/advertis-manage/popular-information",
      },
      {
        path: "/advertis-manage/popular-information/detail",
        meta: {
          icon: "ios-browsers",
          title: "热门资讯详情",
          sidehead: "热门资讯详情-广告素材管理-后台管理系统",
          hideInMenu: true,
          access: ["/material/card/article/detail"],
        },
        name: "popular-information-detail",
        component: "view/advertis-manage/popular-information/detail",
      },
      {
        path: "/advertis-manage/popular-information/edit",
        meta: {
          icon: "ios-browsers",
          title: "热门资讯编辑",
          sidehead: "热门资讯编辑-广告素材管理-后台管理系统",
          hideInMenu: true,
          access: ["/material/card/article/save"],
        },
        name: "popular-information-edit",
        component: "view/advertis-manage/popular-information/edit",
      },
      {
        path: "/advertis-manage/carousel-img",
        meta: {
          icon: "ios-browsers",
          title: "轮播图内容",
          sidehead: "轮播图内容-后台管理系统",
          access: ["/advertis-manage/carousel-img"],
          keepAlive: true,
        },
        name: "advertis-manage-carousel-img",
        component: "view/advertis-manage/carousel-img",
      },
      {
        path: "/advertis-manage/carousel-img/scan",
        meta: {
          icon: "ios-browsers",
          title: "轮播图内容查看",
          sidehead: "轮播图内容查看-后台管理系统",
          hideInMenu: true,
          access: ["/material/card/banner/detail"],
        },
        name: "advertis-manage-carousel-img-scan",
        component: "view/advertis-manage/carousel-img/view",
      },
      {
        path: "/advertis-manage/carousel-img/detail",
        meta: {
          icon: "ios-browsers",
          title: "轮播图内容编辑",
          sidehead: "轮播图内容编辑-后台管理系统",
          hideInMenu: true,
          access: ["/material/card/banner/save"],
        },
        name: "advertis-manage-carousel-img-detail",
        component: "view/advertis-manage/carousel-img/detail",
      },
      {
        path: "/advertis-manage/personalize-notice",
        meta: {
          icon: "ios-browsers",
          title: "个性通知",
          sidehead: "个性通知-后台管理系统",
          access: ["a32cde58-b820-4c6f-b690-abc54a8816ed"],
          keepAlive: true,
        },
        name: "AdvertiseManagePresonalizeNotification",
        component: "view/advertis-manage/personalize-notice/index.vue",
      },
      {
        path: "/advertis-manage/personalize-notice/add",
        meta: {
          title: "个性通知添加",
          sidehead: "个性通知添加-后台管理系统",
          hideInMenu: true,
        },
        name: "AdvertiseManagePersonalizeNotificationAdd",
        component: "view/advertis-manage/personalize-notice/detail.vue",
      },
      {
        path: "/advertis-manage/personalize-notice/edit/:id",
        meta: {
          title: "个性通知编辑",
          sidehead: "个性通知编辑-后台管理系统",
          hideInMenu: true,
        },
        name: "AdvertiseManagePersonalizeNotificationEdit",
        component: "view/advertis-manage/personalize-notice/detail.vue",
      },
    ],
  },
  //广告位管理
  {
    path: "/advertise_location",
    name: "advertise-location",
    component: 'Main',
    meta: {
      title: "广告位管理",
      icon: "ios-cog",
      access: ["/ad-position/manage"],
    },
    children: [
      {
        path: "/advertise_location/home_configuration",
        meta: {
          icon: "ios-browsers",
          title: "首页配置",
          sidehead: "首页配置-后台管理系统",
          access: ["/app/config-page/loan-supermarket-home/detail"],
          keepAlive: true,
        },
        name: "advertise-location-home-configuration",
        component: "view/advertise-location/home-configuration",
      },
      {
        path: "/advertise_location/home_configuration/edit",
        meta: {
          icon: "ios-browsers",
          title: "首页新增/新增",
          sidehead: "首页新增/新增-后台管理系统",
          access: ["/app/config-page/loan-supermarket-home/detail/edit"],
        },
        name: "advertise-location-home-configuration-edit",
        component: "view/advertise-location/home-configuration/new.vue",
      },
      {
        path: "/advertise_location/cashloan_configuration",
        meta: {
          icon: "ios-browsers",
          title: "现金贷首页配置",
          sidehead: "现金贷首页配置-后台管理系统",
          access: ["/app/config-page/cash-loan-home/detail"],
        },
        name: "advertise-location-cashloan-configuration",
        component: "view/advertise-location/cashloan-configuration",
      },
      {
        path: "/advertise_location/home_credit_life",
        meta: {
          icon: "ios-browsers",
          title: "信用生活页配置",
          sidehead: "信用生活页配置-后台管理系统",
          access: ["/app/config-page/credit-life/detail"],
        },
        name: "advertise-location-home-credit-life",
        component: "view/advertise-location/home-credit-life",
      },
      {
        path: "/advertise_location/fast",
        meta: {
          icon: "ios-browsers",
          title: "极速贷页配置",
          sidehead: "极速贷页配置-后台管理系统",
          access: ["/app/config-page/fast"],
        },
        name: "advertise-location-home-fast",
        component: "view/advertise-location/fast",
      },
      {
        path: "/advertise_location/blank",
        meta: {
          icon: "ios-browsers",
          title: "空白页配置",
          sidehead: "空白页配置-后台管理系统",
          access: ["/app/config-page/blank"],
        },
        name: "advertise-location-home-blank",
        component: "view/advertise-location/blank",
      },
      {
        path: "/advertise_location/user_center",
        meta: {
          icon: "ios-browsers",
          title: "个人中心配置",
          sidehead: "个人中心配置-后台管理系统",
          access: ["/app/config-page/personal-center/detail"],
          keepAlive: true,
        },
        name: "advertise-location-user-center",
        component: "view/advertise-location/user-center",
      },
      {
        path: "/advertise_location/apply_result",
        meta: {
          icon: "ios-browsers",
          title: "申请结果页配置",
          sidehead: "申请结果页配置-后台管理系统",
          access: ["/app/config-page/api-apply/list"],
        },
        name: "advertise-location-apply-result",
        component: "view/advertise-location/apply-result",
      },
      {
        path: "/advertise_location/apply_result/config",
        meta: {
          icon: "ios-browsers",
          title: "申请结果页配置详情",
          sidehead: "申请结果页配置详情-后台管理系统",
          access: ["/app/config-page/api-apply/add-update"],
          hideInMenu: true,
        },
        name: "advertise-location-apply-result-config",
        component: "view/advertise-location/apply-result/update-config",
      },
      {
        path: "/advertise_location/bottom_menu_config",
        meta: {
          icon: "ios-browsers",
          title: "底部菜单配置",
          sidehead: "底部菜单配置-后台管理系统",
          access: ["deeff4a4-73ac-4847-9665-c341e509f038"],
          keepAlive: true,
        },
        name: "AdvertiseLocationBottomMenuConfig",
        component: "view/advertise-location/bottom-config/index.vue",
      },
      {
        path: "/advertise_location/bottom_menu_config/add",
        meta: {
          title: "底部菜单配置新增",
          sidehead: "底部菜单配置新增-后台管理系统",
          hideInMenu: true,
        },
        name: "AdvertiseLocationBottomMenuConfigAdd",
        component: "view/advertise-location/bottom-config/detail.vue",
      },
      {
        path: "/advertise_location/bottom_menu_config/edit/:id",
        meta: {
          title: "底部菜单配置编辑",
          sidehead: "底部菜单配置编辑-后台管理系统",
          hideInMenu: true,
        },
        name: "AdvertiseLocationBottomMenuConfigEdit",
        component: "view/advertise-location/bottom-config/detail.vue",
      },
    ],
  },
  // 极速贷产品设置
  {
    path: "/product-manage",
    name: "product_manage",
    component: 'Main',
    meta: {
      title: "产品管理",
      icon: "ios-happy-outline",
      access: ["/settlement-manage"],
    },
    children: [
      {
        path: "product-category-manage",
        name: "product_category_manage",
        meta: {
          icon: "md-list",
          title: "分类设置",
          sidehead: "产品分类设置-后台管理系统",
          access: ["view/product/product-classify.html"],
        },
        component: "view/product/category",
      },
      {
        path: "product-tag-manage",
        name: "product_tag_manage",
        meta: { icon: "md-list", title: "标签设置", sidehead: "产品标签设置-后台管理系统", access: ["view/product/product-title.html"] },
        component: "view/product/tag",
      },
      {
        path: "product-online-manage",
        name: "product_online_manage",
        meta: {
          icon: "md-list",
          title: "线上产品",
          sidehead: "线上产品-后台管理系统",
          access: ["view/product/product-manage-new.html?productStatus=1"],
          keepAlive: true,
        },
        component: "view/product/list/product-online-list",
      },
      {
        path: "product-offline-manage",
        name: "product_offline_manage",
        meta: {
          icon: "md-list",
          title: "线下产品",
          sidehead: "线下产品-后台管理系统",
          access: ["view/product/product-manage-new.html?productStatus=1"],
          keepAlive: true,
        },
        component: "view/product/list/product-offline-list",
      },
      {
        path: "product-unsubmit-manage",
        name: "product_unsubmit_manage",
        meta: {
          icon: "md-list",
          title: "待上线产品",
          sidehead: "待上线产品-后台管理系统",
          access: ["view/product/product-manage-new.html?productStatus=1"],
          keepAlive: true,
        },
        component: "view/product/list/product-unsubmit-list",
      },
      {
        path: "product-sort-manage",
        name: "product_sort_manage",
        meta: { icon: "md-list", title: "线上产品排序", sidehead: "线上产品排序-后台管理系统", access: ["view/product/product-sort.html"] },
        component: "view/product/sort",
      },
      {
        path: "product-recommend-manage",
        name: "product_recommend_manage",
        meta: {
          icon: "md-list",
          title: "产品类型排序",
          sidehead: "产品类型排序-后台管理系统",
          access: ["view/product/product-recommend-sort.html"],
        },
        component: "view/product/recommend",
      },
      {
        path: "product-detail",
        name: "product_detail",
        meta: { icon: "md-list", title: "产品详情", sidehead: "产品详情-后台管理系统", access: [], hideInMenu: true },
        component: "view/product/list/detail",
      },
      {
        path: "product-edit",
        name: "product_edit",
        meta: { icon: "md-list", title: "产品编辑", sidehead: "产品编辑-后台管理系统", access: [], hideInMenu: true },
        component: "view/product/list/edit",
      },
      {
        path: "/data-statistics/product-data",
        name: "product-data",
        meta: {
          title: "产品行为统计",
          icon: "ios-browsers",
          sidehead: "产品行为统计-后台管理系统",
          access: ["view/data/product-rep.html"],
          keepAlive: true,
        },
        component: "view/data-statistics/product-data",
      },
      {
        path: "/data-statistics/product-data2",
        name: "product-data2",
        meta: {
          title: "新产品行为统计",
          icon: "ios-browsers",
          sidehead: "新产品行为统计-后台管理系统",
          access: ["view/data/product-data.html"],
          keepAlive: true,
        },
        component: "view/data-statistics/product-data2",
      },
      {
        path: "/data-statistics/product-data/product-list",
        name: "data-statistics-product-list",
        meta: {
          icon: "ios-browsers",
          title: "产品行为详情",
          sidehead: "产品行为详情-后台管理系统",
          hideInMenu: true,
          access: ["/product/behavior/data"],
        },
        component: "view/data-statistics/product-data/product-list",
      },
      {
        path: "/data-statistics/product-data2/product-list",
        name: "data-statistics-product-list2",
        meta: {
          icon: "ios-browsers",
          title: "新产品行为详情",
          sidehead: "产品行为详情-后台管理系统",
          hideInMenu: true,
          access: ["/product/behavior/data"],
        },
        component: "view/data-statistics/product-data2/product-list",
      },
      {
        path: "/data-statistics/product-data/product-list/log-list",
        name: "data-statistics-product-list-log-list",
        meta: {
          icon: "ios-browsers",
          title: "修改日志",
          sidehead: "修改日志-后台管理系统",
          hideInMenu: true,
          access: ["/product/behavior/review/day/data/history"],
        },
        component: "view/data-statistics/product-data/product-list/log-list",
      },
      {
        path: "/data-statistics/product-data/reg-detail",
        name: "data-statistics-product-reg-detail",
        meta: {
          icon: "ios-browsers",
          title: "注册详情列表",
          sidehead: "注册详情列表-后台管理系统",
          hideInMenu: true,
          access: ["/product/behavior/res/list"],
        },
        component: "view/data-statistics/product-data/reg-detail",
      },
      // 产品管理
      {
        path: "product",
        meta: {
          icon: "ios-book-outline",
          title: "全部产品",
          sidehead: "产品管理-全部产品",
          access: ["3fef77cd-b998-4f22-bde9-0896c69c4039"],
          keepAlive: true,
        },
        name: "product-management",
        component: "view/product-service-management/product/index.vue",
      },
      {
        path: "product-mine",
        meta: {
          icon: "ios-book-outline",
          title: "我的产品",
          sidehead: "产品管理-我的产品",
          access: ["22d28cd2-c1dd-4808-b1f1-1b7b937932c3"],
          keepAlive: true,
        },
        name: "product-management-mine",
        component: "view/product-service-management/product/mine.vue",
      },
      {
        path: "product-audit",
        meta: {
          icon: "ios-flash",
          title: "产品审核",
          sidehead: "产品管理-产品审核",
          access: ["54f08c19-2146-41ab-aee5-62af1a38d179"],
          keepAlive: true,
        },
        name: "product-management-audit",
        component: "view/product-service-management/product/audit.vue",
      },
      {
        path: "product-detail/:mode/:id",
        meta: {
          hideInMenu: true,
          title: "产品详情",
        },
        name: "product-management-detail",
        component: "view/product-service-management/product/detail.vue",
      },
    ],
  },
  // 商户管理
  {
    path: "/merchant",
    name: "merchant",
    component: 'Main',
    meta: {
      title: "商户管理",
      icon: "ios-browsers",
      access: ["/merchant"],
    },
    children: [
      {
        path: "business-approving",
        name: "business-approving",
        meta: {
          icon: "md-list",
          title: "我审核的商户",
          sidehead: "商户审核-后台管理系统",
          access: ["view/business/business-approving-new-credit.html"],
          keepAlive: true,
        },
        component: "view/bank-product/reviewed-list",
      },

      {
        path: "business-my",
        name: "business-my",
        meta: {
          icon: "md-list",
          title: "我负责的商户",
          sidehead: "我的商户-后台管理系统",
          access: ["view/business/business-my-new-credit.html"],
          keepAlive: true,
        },
        component: "view/bank-product/submitter-list",
      },
      {
        path: "business-manage",
        name: "business_manage",
        meta: {
          icon: "md-list",
          title: "所有商户",
          sidehead: "助贷商户-后台管理系统",
          access: ["view/business/business-manage-new-credit.html"],
          keepAlive: true,
        },
        component: "view/bank-product/organization-list",
      },
      {
        path: "/bank-product/organization-list/new-edit",
        meta: {
          icon: "ios-pricetag",
          title: "新增机构",
          sidehead: "机构列表-后台管理系统",
          access: ["/bank-product/organization-list/new-edit"],
        },
        name: "bank-product_organization-list_new-edit",
        component: "view/bank-product/organization-list/new-edit",
      },
    ],
  },
  // 推广管理
  {
    path: "/popularize",
    name: "popularize",
    component: 'Main',
    meta: {
      title: "推广管理",
      icon: "ios-happy-outline",
      access: ["/popularize"],
    },
    children: [
      {
        path: "plan-loan-manage",
        name: "PlanLoan",
        meta: {
          icon: "md-list",
          title: "助贷推广计划",
          sidehead: "助贷推广计划-后台管理系统",
          access: ["view/plan/plan-manage-new-credit.html"],
          keepAlive: true,
        },
        component: "view/popularize/loan/index.vue",
      },
      {
        path: "m-plan-loan-manage",
        name: "PlanLoanMine",
        meta: {
          icon: "md-list",
          title: "我的助贷推广计划",
          sidehead: "我的助贷推广计划",
          access: ["view/plan/m-plan-loan-manage"],
          keepAlive: true,
        },
        component: "view/popularize/loan/mine.vue",
      },
      {
        path: "plan-loan-new",
        name: "PlanLoanNew",
        meta: {
          icon: "ios-pricetag",
          title: "新增/编辑推广",
          sidehead: "推广-后台管理系统",
          access: ["/bank-product/popularize-list/new"],
        },
        component: "view/popularize/loan/new.vue",
      },
      {
        path: "plan-peer-manage",
        name: "PlanPeerManage",
        meta: { icon: "logo-buffer", title: "同业推广计划", keepAlive: true, sidehead: "同业推广计划-后台管理系统", access: ["1c076d9a-f3c9-4f67-b3ec-73a540947fa0"] },
        component: "view/popularize/plan-peer-manage/index.vue",
      },
      {
        path: "plan-peer-manage-mine",
        name: "planPeerManageMine",
        meta: {
          icon: "logo-buffer",
          title: "我的同业推广计划",
          sidehead: "我的同业推广计划-后台管理系统",
          access: ["aaa5253e-6efd-4784-a688-9220c95dc950"],
          keepAlive: true,
        },
        component: "view/popularize/plan-peer-manage/mine.vue",
      },
      {
        path: "plan-peer-manage-add",
        name: "PlanPeerManageAdd",
        meta: { title: "新增同业推广计划", sidehead: "新增同业推广计划-后台管理系统", hideInMenu: true },
        component: "view/popularize/plan-peer-manage/detail.vue",
      },
      {
        path: "plan-peer-manage-edit/:id",
        name: "PlanPeerManageEdit",
        meta: { title: "编辑同业推广计划", sidehead: "编辑同业推广计划-后台管理系统", hideInMenu: true },
        component: "view/popularize/plan-peer-manage/detail.vue",
      },
      {
        path: "plan-fast",
        name: "PlanFast",
        meta: {
          icon: "logo-buffer",
          title: "极速贷推广计划",
          sidehead: "极速贷推广计划-后台管理系统",
          access: ["24aff8a7-f79a-4577-a4b2-4bd19bdfb37c"],
          keepAlive: true,
        },
        component: "view/popularize/fast/index.vue",
      },
      {
        path: "plan-fast-mine",
        name: "PlanFastMine",
        meta: {
          icon: "logo-buffer",
          title: "我的极速贷推广计划",
          sidehead: "我的极速贷推广计划-后台管理系统",
          access: ["65835b3d-1810-4e65-a79b-da8af729d7c6"],
          keepAlive: true,
        },
        component: "view/popularize/fast/mine.vue",
      },
      {
        path: "plan-fast-add",
        name: "PlanFastAdd",
        meta: { title: "新增极速贷推广计划", sidehead: "新增极速贷推广计划-后台管理系统", hideInMenu: true },
        component: "view/popularize/fast/detail.vue",
      },
      {
        path: "plan-fast-edit/:id",
        name: "PlanFastEdit",
        meta: { title: "新增极速贷推广计划", sidehead: "新增极速贷推广计划-后台管理系统", hideInMenu: true },
        component: "view/popularize/fast/detail.vue",
      },
      {
        path: "plan-peer-manage-config",
        name: "planPeerManageConfig",
        meta: { icon: "logo-buffer", title: "推广设置", sidehead: "推广设置-后台管理系统", access: ["a0a49083-042f-43b6-9a2b-b80913ab9579"] },
        component: "view/popularize/config/index.vue",
      },
      {
        path: "rules",
        meta: {
          icon: "ios-photos",
          title: "撞库/预准入规则管理",
          sidehead: "API管理-撞库/预准入规则管理",
          access: ["329d87f9-4ea8-4b75-a0cd-87b3c8d1d8f7"],
          keepAlive: true,
        },
        name: "api-management-rules",
        component: "view/api-management/rules",
      },
      {
        path: "city-star",
        meta: {
          icon: "ios-star",
          title: "城市星级统计",
          sidehead: "推广设置-城市星级统计",
          access: ["3272e32c-63d8-49b7-afce-f481f4cf9e63"],
          keepAlive: true,
        },
        name: "CityStar",
        component: "view/popularize/city-star/index.vue",
      },
    ],
  },
  //银行贷产品设置
  {
    path: "/product-settings",
    name: "product_settings",
    component: 'Main',
    meta: {
      title: "助贷管理",
      icon: "ios-cog",
      access: ["/xindaiproduct"],
    },
    children: [
      {
        path: "list",
        meta: { icon: "md-people", title: "推广申请订单", keepAlive: true, sidehead: "推广申请订单-后台管理系统", access: ["/xindai/order-manage"] },
        name: "xd_order_list",
        component: "view/order-manage/list",
      },
      {
        path: "list/detail",
        name: "xd_order_list_detail",
        meta: {
          icon: "ios-browsers",
          title: "推广申请订单详情",
          sidehead: "推广申请订单详情-后台管理系统",
          hideInMenu: true,
        },
        component: "view/order-manage/list/detail",
      },
      {
        path: "/bank-product/product-list",
        meta: {
          icon: "ios-pricetag",
          title: "产品列表",
          sidehead: "机构列表-后台管理系统",
          access: ["/bank-product/product-list"],
        },
        name: "bank-product_product-list",
        component: "view/bank-product/product-list",
      },
      {
        path: "/bank-product/product-list/new",
        meta: {
          icon: "ios-pricetag",
          title: "新增产品",
          sidehead: "机构列表-后台管理系统",
          access: ["/bank-product/product-list/new"],
        },
        name: "bank-product_product-list_new",
        component: "view/bank-product/product-list/new",
      },
      {
        path: "/bank-product/reviewed-list/new",
        meta: {
          icon: "ios-pricetag",
          title: "审核人列表",
          sidehead: "机构列表-后台管理系统",
          access: ["/bank-product/reviewed-list/new"],
        },
        name: "bank-product_reviewed-list_new",
        component: "view/bank-product/reviewed-list/new",
      },
      {
        path: "/bank-product/account-number",
        meta: {
          icon: "ios-pricetag",
          title: "机构账号",
          sidehead: "机构列表-后台管理系统",
          access: ["/bank-product/account-number"],
        },
        name: "bank-product_account-number",
        component: "view/bank-product/account-number",
      },

      {
        path: "/bank-product/organization-list/api-edit",
        meta: {
          icon: "ios-pricetag",
          title: "对接方式",
          sidehead: "对接方式-后台管理系统",
          access: ["/bank-product/organization-list/api-edit"],
        },
        name: "bank-product_organization-list_api-edit",
        component: "view/bank-product/organization-list/api-edit",
      },

      {
        path: "/product-settings/label-manager",
        name: "product_settings_label_manager",
        meta: {
          icon: "md-list",
          title: "产品标签管理",
          sidehead: "产品标签管理-后台管理系统",
          access: ["/xindai/product/tag"],
        },
        component: "view/product-settings/label-manager",
      },
      {
        path: "/product-settings/product-sort",
        name: "product_settings_product_sort",
        meta: {
          icon: "md-list",
          title: "线上产品排序",
          sidehead: "线上产品排序-后台管理系统",
          access: ["/xindai/product/sort"],
        },
        component: "view/product-settings/product-sort",
      },
      {
        path: "product-loan-manage",
        name: "product_loan_manage",
        meta: {
          icon: "md-list",
          title: "产品管理",
          sidehead: "产品管理-后台管理系统",
          access: [" view/product/product-manage-new-credit.html"],
        },
        component: "view/product-settings/list",
      },
      {
        path: "product-loan-statistics",
        name: "product_loan_statistics",
        meta: {
          icon: "md-list",
          title: "产品订单统计",
          sidehead: "产品统计-后台管理系统",
          access: [" view/product/product-manage-product_loan_statistics.html"],
          keepAlive: true,
        },
        component: "view/product-settings/statistics",
      },
      {
        path: "product-loan-statistics-detail",
        name: "product_loan_statistics-detail",
        meta: {
          icon: "md-list",
          title: "产品订单统计",
          sidehead: "产品统计-后台管理系统",
          hideInMenu: true,
          access: [" view/product/product-manage-product_loan_statistics.html"],
        },
        component: "view/product-settings/statistics-detail",
      },
      {
        path: "product-loan-statistics-my",
        name: "product_loan_statistics-my",
        meta: {
          icon: "md-list",
          title: "我的商户推广统计",
          sidehead: "我的商户推广统计-后台管理系统",
          access: [" view/product/product-manage-product_loan_statistics2.html"],
          keepAlive: true,
        },
        component: "view/product-settings/mystatistics",
      },
      {
        path: "product-loan-statistics-xd-product",
        name: "product_loan_statistics_xd_product",
        meta: {
          icon: "md-list",
          title: "助贷咨询数据统计",
          sidehead: "助贷咨询数据统计-后台管理系统",
          access: ["d7b73c10-e39c-4bdc-b50b-af062620ce83"],
          keepAlive: true,
        },
        component: "view/product-settings/xdProductStatistics",
      },
      {
        path: "myproduct-loan-statistics-xd-product",
        name: "myproduct_loan_statistics_xd_product",
        meta: {
          icon: "md-list",
          title: "我的助贷咨询统计",
          sidehead: "我的助贷咨询统计-后台管理系统",
          access: ["bda32a2a-4b99-4176-8cfa-5e9fdab07237"],
          keepAlive: true,
        },
        component: "view/product-settings/myxdProductStatistics",
      },
      {
        path: "institutional-transaction",
        meta: {
          icon: "ios-pricetag",
          title: "助贷商户账单",
          sidehead: "助贷商户账单-后台管理系统",
          access: ["institutional-transaction"],
        },
        name: "institutional-transaction",
        component: "view/product-settings/institutional-transaction",
      },
      {
        path: "institutional-transaction-principal",
        meta: {
          icon: "ios-pricetag",
          title: "我的助贷商户账单",
          sidehead: "我的助贷商户账单记录-后台管理系统",
          access: ["institutional-transaction-principal"],
        },
        name: "institutional-transaction-principal",
        component: "view/product-settings/institutional-transaction/principal.vue",
      },
      //
      {
        path: "institutional-checkout",
        name: "institutional_checkout",
        meta: {
          icon: "ios-pricetag",
          title: "助贷商户财务审核",
          sidehead: "助贷商户财务审核-后台管理系统",
          access: ["institutional-checkout"],
          keepAlive: true,
        },
        component: "view/product-settings/institutional-checkout",
      },
      {
        path: "institutional-transaction-new",
        meta: {
          icon: "ios-pricetag",
          title: "助贷商户账单-账单详情",
          sidehead: "助贷商户账单-账单详情-后台管理系统",
          access: ["institutional-checkout-particulars"],
        },
        name: "institutional-transaction-new",
        component: "view/product-settings/institutional-transaction/particulars.vue",
      },

      {
        path: "institutional-transaction-detail",
        meta: {
          icon: "ios-pricetag",
          title: "助贷商户账单-消耗明细统计",
          sidehead: "助贷商户账单-消耗明细统计-后台管理系统",
          access: ["institutional-checkout-particulars"],
        },
        name: "institutional-transaction-detail",
        component: "view/product-settings/institutional-transaction/detail.vue",
      },
      // detail
      {
        path: "product-loan-manage/scan",
        name: "product_loan_manage_scan",
        meta: { icon: "md-list", title: "产品详情", sidehead: "产品详情-后台管理系统", access: ["product-loan-manage/scan"] },
        component: "view/product-settings/list/detail",
      },
      {
        path: "product-loan-manage/detail",
        name: "product_loan_manage_detail",
        meta: { icon: "md-list", title: "产品编辑", sidehead: "产品编辑-后台管理系统", access: ["product-loan-manage/detail"] },
        component: "view/product-settings/list/edit",
      },
      // 同业平台管理 peer-platform
      {
        path: "peer-platform",
        name: "peer-platform",
        meta: {
          title: "同业平台管理",
          icon: "ios-chatboxes",
          access: ["peer-platform"],
        },
        component: "view/product-settings/peer-platform",
      },
      {
        path: "peer-platform/new",
        meta: {
          icon: "ios-pricetag",
          title: "新增三方同业平台",
          sidehead: "新增三方同业平台-后台管理系统",
          access: ["peer-platform/new"],
        },
        name: "peer-platform/new",
        component: "view/product-settings/peer-platform/new.vue",
      },
      {
        path: "star-statistics",
        meta: {
          icon: "ios-pricetag",
          title: "推广计划星级统计",
          sidehead: "推广计划星级统计-后台管理系统",
          access: ["f1b0831d-d854-4092-88e2-e67a829f1625"],
          keepAlive: true,
        },
        name: "star_statistics",
        component: "view/product-settings/starstatistics",
      },
      {
        path: "channelstar-statistics",
        meta: {
          icon: "ios-pricetag",
          title: "渠道星级统计",
          sidehead: "渠道星级统计-后台管理系统",
          access: ["a8ea01da-b6b2-4e34-b1b5-9c7e10db94ac"],
          keepAlive: true,
        },
        name: "channelstar_statistics",
        component: "view/product-settings/channelstarstatistics",
      },
      {
        path: "mystar-statistics",
        meta: {
          icon: "ios-pricetag",
          title: "我的推广计划星级统计",
          sidehead: "我的推广计划星级统计-后台管理系统",
          access: ["187cb735-826c-41ba-b62c-3f1ac0170cce"],
          keepAlive: true,
        },
        name: "mystar_statistics",
        component: "view/product-settings/mystarstatistics",
      },
      {
        path: "mychannelstar-statistics",
        meta: {
          icon: "ios-pricetag",
          title: "我的渠道星级统计",
          sidehead: "我的渠道星级统计-后台管理系统",
          access: ["7daf75a8-5a83-4911-ba74-3992ceccacf4"],
          keepAlive: true,
        },
        name: "mychannelstar-statistics",
        component: "view/product-settings/mychannelstarstatistics",
      },
    ],
  },
  // 同业共享业务管理
  {
    path: "/peer-sharing-service-management",
    name: "PeerSharingServiceManagement",
    component: 'Main',
    meta: {
      title: "同业共享业务管理",
      icon: "md-infinite",
      access: ["7be465e2-83bd-45e7-a5f4-fbcc2ab32016"],
    },
    children: [
      {
        path: "statistic",
        name: "PeerSharingStatistic",
        component: "view/peer-sharing-service-management/statistic/index.vue",
        meta: {
          title: "同业共享数据统计",
          icon: "ios-stats",
          access: ["6f7eed21-91e4-41c1-82db-800814abe532"],
          keepAlive: true,
        },
      },
      {
        path: "statistic-mine",
        name: "PeerSharingStatisticMine",
        component: "view/peer-sharing-service-management/statistic/index-mine.vue",
        meta: {
          title: "我的同业数据统计",
          icon: "ios-stats",
          access: ["6be47d5c-65a0-49d9-a6fc-b8bb0573bb46"],
          keepAlive: true,
        },
      },
    ],
  },
  //渠道管理
  {
    path: "/channel",
    name: "channel",
    component: 'Main',
    meta: {
      title: "渠道管理",
      icon: "ios-cog",
      access: ["/channel"],
    },
    children: [
      {
        path: "type",
        meta: { icon: "ios-browsers", title: "渠道类型管理", sidehead: "渠道类型管理-后台管理系统", access: ["/channel/type"] },
        name: "channel_type",
        component: "view/channel/type",
      },
      {
        path: "manager",
        meta: { icon: "ios-albums", title: "全部渠道", keepAlive: true, sidehead: "全部渠道-后台管理系统", access: ["/channel/manager"] },
        name: "channel_manager",
        component: "view/channel/manager",
      },
      {
        path: "manager-mine",
        meta: { icon: "ios-albums-outline", title: "我的渠道", keepAlive: true, sidehead: "我的渠道-后台管理系统", access: ["/channel/mlist"] },
        name: "channel_manager_mine",
        component: "view/channel/manager/mine",
      },
      {
        path: "link",
        meta: { icon: "ios-apps", title: "全部链接", keepAlive: true, sidehead: "全部链接-后台管理系统", access: ["/address/manager"] },
        name: "channel_link",
        component: "view/channel/link",
      },
      {
        path: "add-link",
        meta: { icon: "md-body", title: "新增链接", sidehead: "新增链接-链接管理-后台管理系统", hideInMenu: true },
        name: "channel_link_add",
        component: "view/channel/link/addlink",
      },
      {
        path: "edit-link",
        meta: { icon: "md-body", title: "编辑链接", sidehead: "编辑链接-链接管理-后台管理系统", hideInMenu: true },
        name: "channel_link_edit",
        component: "view/channel/link/addlink/edit",
      },
      {
        path: "manager-link",
        meta: { icon: "ios-apps-outline", title: "我的链接", keepAlive: true, sidehead: "我的链接-后台管理系统", access: ["/address/mlist"] },
        name: "channel_link_mine",
        component: "view/channel/link/mine",
      },
      {
        path: "black",
        meta: { icon: "md-bug", title: "黑名单管理", keepAlive: true, sidehead: "黑名单管理-后台管理系统", access: ["/black/list"] },
        name: "channel_black",
        component: "view/channel/black",
      },
      {
        path: "download-url",
        meta: {
          icon: "ios-download-outline",
          title: "下载地址管理",
          sidehead: "下载地址管理-后台管理系统",
          access: ["/download-url/list"],
        },
        name: "download_url",
        component: "view/channel/download-url",
      },
      {
        path: "recipients",
        meta: { icon: "md-bug", title: "收件人管理", sidehead: "收件人管理-后台管理系统", access: ["/black/list"] },
        name: "channel_mail",
        component: "view/channel/recipients",
      },
      {
        path: "release_platform_setting_add",
        meta: { title: "投放平台设置添加", sidehead: "投放平台设置添加-后台管理系统", notCache: true, hideInMenu: true },
        name: "ReleasePlatformSettingAdd",
        component: "view/channel/release-platform-setting/add.vue",
      },
      {
        path: "package",
        meta: {
          icon: "md-cube",
          title: "渠道包管理",
          sidehead: "渠道包管理-后台管理系统",
          access: ["1cd1f64f-f12c-4a73-85d8-00ea360527c0"],
          notCache: true,
        },
        name: "ChannelPackage",
        component: "view/channel/channel-package",
      },
      {
        path: "package/add",
        meta: { icon: "", title: "渠道包新增", sidehead: "渠道包新增-后台管理系统", hideInMenu: true, notCache: true },
        name: "ChannelPackageAdd",
        component: "view/channel/channel-package/add.vue",
      },
      {
        path: "package/edit/:id",
        meta: { icon: "", title: "渠道包编辑", sidehead: "渠道包编辑-后台管理系统", hideInMenu: true, notCache: true },
        name: "ChannelPackageEdit",
        component: "view/channel/channel-package/add.vue",
      },
      {
        path: "rules",
        meta: {
          icon: "md-list-box",
          title: "渠道规则管理",
          sidehead: "渠道规则管理-后台管理系统",
          access: ["96bd88e2-f60e-478d-8bf5-771437a799a2"],
          notCache: true,
        },
        name: "ChannelRules",
        component: "view/channel/channel-rule",
      },
      {
        path: "rules/add",
        meta: { icon: "", title: "渠道规则新增", sidehead: "渠道规则新增-后台管理系统", hideInMenu: true },
        name: "ChannelRulesAdd",
        component: "view/channel/channel-rule/detail.vue",
      },
      {
        path: "rules/edit/:id",
        meta: { icon: "", title: "渠道规则编辑", sidehead: "渠道规则编辑-后台管理系统", hideInMenu: true },
        name: "ChannelRulesEdit",
        component: "view/channel/channel-rule/detail.vue",
      },
      {
        path: "exclude-query",
        meta: {
          icon: "md-log-out",
          title: "渠道排除查询",
          sidehead: "渠道排除查询-后台管理系统",
          access: ["442ff35b-cdc3-4a53-83cb-5d29f4ba5bdb"],
          keepAlive: true,
        },
        name: "ExcludeQuery",
        component: "view/channel/exclude-query",
      },
    ],
  },
  //渠道管理
  {
    path: "/channelattribution",
    name: "channelattribution",
    component: 'Main',
    meta: {
      title: "渠道归因",
      icon: "ios-cog",
      access: ["ad08f78f-98ea-4563-baa9-0407a37e099c"],
    },
    children: [
      {
        path: "rulemanage",
        meta: { icon: "ios-browsers", title: "规则管理", sidehead: "渠道归因-后台管理系统", access: ["b055ec44-a02b-4e39-b0a7-78d5a750ecae"] },
        name: "channelattribution-rule",
        component: "view/channelattribution/rulemanage",
      },
      {
        path: "analysis",
        meta: { icon: "ios-browsers", title: "归因调配分析", keepAlive: true, sidehead: "渠道归因-后台管理系统", access: ["6a6a6e9d-6fee-40e6-8cd4-5e376e5b5750"] },
        name: "channelattribution-analysis",
        component: "view/channelattribution/analysis",
      },
    ],
  },
  // api管理
  {
    path: "/api_management",
    name: "api_management",
    component: 'Main',
    meta: {
      title: "API管理",
      icon: "ios-settings",
      access: ["/api-management"],
    },
    children: [
      {
        path: "loan",
        meta: {
          icon: "",
          title: "助贷API",
          sidehead: "API管理-助贷API",
          access: ["/api-management/loan"],
          keepAlive: true,
        },
        name: "api-management-loan",
        component: "view/api-management/loan",
      },
      {
        path: "channel",
        meta: {
          icon: "",
          title: "渠道API",
          sidehead: "API管理-渠道API",
          access: ["/api-management/channel"],
          keepAlive: true,
        },
        name: "api-management-channel",
        component: "view/api-management/channel",
      },
      {
        path: "product",
        meta: {
          icon: "",
          title: "产品API",
          sidehead: "API管理-产品API",
          access: ["061ef3de-2ba6-4044-86be-7589beb8bcab"],
          keepAlive: true,
        },
        name: "api-management-product",
        component: "view/api-management/product",
      },
      {
        path: "create-product",
        meta: {
          icon: "",
          title: "新增产品API",
          sidehead: "API管理-新增产品API",
          hideInMenu: true,
          access: [],
        },
        name: "api-management-create-product",
        component: "view/api-management/product/create.vue",
      },
      {
        path: "create-product/:id",
        meta: {
          icon: "",
          title: "编辑产品API",
          sidehead: "API管理-编辑产品API",
          hideInMenu: true,
          access: [],
        },
        name: "api-management-edit-product",
        component: "view/api-management/product/create.vue",
      },
      {
        path: "create",
        meta: {
          icon: "",
          title: "新增助贷API",
          sidehead: "API管理-新增助贷API",
          hideInMenu: true,
          access: ["/api-management/loan/create"],
        },
        name: "api-management-create",
        component: "view/api-management/loan/create.vue",
      },
      {
        path: "create-channel",
        meta: {
          icon: "",
          title: "新增渠道API",
          sidehead: "API管理-新增渠道API",
          hideInMenu: true,
          access: ["/api-management/channel/create"],
        },
        name: "api-management-create-channel",
        component: "view/api-management/channel/create.vue",
      },
      {
        path: "create-channel/:id",
        meta: {
          icon: "",
          title: "编辑渠道API",
          sidehead: "API管理-编辑渠道API",
          hideInMenu: true,
        },
        name: "api-management-edit-channel",
        component: "view/api-management/channel/create.vue",
      },
    ],
  },
  // 产品和服务管理
  {
    path: "/product_service_management",
    name: "product_service_management",
    component: 'Main',
    meta: {
      title: "服务管理",
      icon: "ios-aperture",
      access: ["/product_service_management"],
    },
    children: [
      // 助贷服务管理
      {
        path: "loan",
        meta: {
          icon: "ios-book-outline",
          title: "助贷服务管理",
          sidehead: "产品与服务管理-助贷服务管理",
          access: ["/product_service_management/loan"],
          keepAlive: true,
        },
        name: "loan-service-management",
        component: "view/product-service-management/loan-service/index.vue",
      },
      {
        path: "loan-mine",
        meta: {
          icon: "ios-book-outline",
          title: "我的助贷服务管理",
          sidehead: "产品与服务管理-我的助贷服务管理",
          access: ["/product_service_management/loan/mine"],
          keepAlive: true,
        },
        name: "loan-service-management-mine",
        component: "view/product-service-management/loan-service/mine.vue",
      },
      {
        path: "loan-audit",
        meta: {
          icon: "ios-flash",
          title: "助贷服务审核",
          sidehead: "产品与服务管理-助贷服务审核",
          access: ["/product_service_management/loan/audit"],
          keepAlive: true,
        },
        name: "loan-service-manangement-audit",
        component: "view/product-service-management/loan-service/audit.vue",
      },
      {
        path: "loan-detail/:mode/:id",
        meta: {
          hideInMenu: true,
          title: "助贷服务详情",
        },
        name: "loan-service-management-detail",
        component: "view/product-service-management/loan-service/detail.vue",
      },
    ],
  },
  //渠道分析
  {
    path: "/channel_analysis",
    name: "channel_analysis",
    component: 'Main',
    meta: {
      title: "渠道分析",
      icon: "ios-settings",
      access: ["/channel/analysis"],
    },
    children: [
      {
        path: "promote-settlement-data",
        meta: {
          icon: "ios-pulse",
          title: "渠道转化率分析",
          sidehead: "渠道转化率分析-后台管理系统",
          access: ["/analysis/apidata"],
          notCache: false,
        },
        name: "channel_promote_api_data1",
        component: "view/channel-analysis/settlement",
      },
      {
        path: "channel-analysis/settlement/product-detail",
        name: "promote-settlement-detail-data",
        meta: {
          icon: "ios-browsers",
          title: "产品详情",
          sidehead: "产品详情-后台管理系统",
          hideInMenu: true,
          access: ["/product/behavior/data"],
        },
        component: "view/channel-analysis/settlement/product-detail",
      },

      {
        path: "promote-api-data",
        meta: {
          icon: "ios-pulse",
          title: "渠道数据分析",
          sidehead: "渠道数据分析-后台管理系统",
          access: ["/analysis/apidata"],
          notCache: false,
        },
        name: "channel_promote_api_data",
        component: "view/channel-analysis/api-data",
      },
      {
        path: "promote-api-data-m",
        meta: {
          icon: "ios-pulse",
          title: "我的渠道数据分析",
          sidehead: "我的渠道数据分析-后台管理系统",
          access: ["/analysis/mapidata"],
          notCache: false,
        },
        name: "channel_promote_api_data_m",
        component: "view/channel-analysis/api-data/mine",
      },
      {
        path: "promote-action",
        meta: {
          icon: "ios-pulse",
          title: "推广行为分析",
          sidehead: "推广行为分析-后台管理系统",
          access: ["/analysis/action"],
          notCache: false,
        },
        name: "channel_promote_action",
        component: "view/channel-analysis/promote-action",
      },
      {
        path: "promote-action-detail",
        meta: {
          icon: "md-body",
          title: "推广行为分析-渠道明细",
          sidehead: "渠道明细-推广行为分析-后台管理系统",
          hideInMenu: true,
          notCache: false,
        },
        name: "channel_promote_action_detail",
        component: "view/channel-analysis/promote-action/detail",
      },
      {
        path: "promote-action-mine",
        meta: {
          icon: "ios-pulse-outline",
          title: "我的推广行为分析",
          sidehead: "我的推广行为分析-后台管理系统",
          access: ["/analysis/maction"],
        },
        name: "channel_promote_action_mine",
        component: "view/channel-analysis/promote-action/mine",
      },
      {
        path: "promote-action-mine-detail",
        meta: { icon: "md-body", title: "我的推广行为分析-渠道明细", sidehead: "渠道明细-我的推广行为分析-后台管理系统", hideInMenu: true },
        name: "channel_promote_action_mine_detail",
        component: "view/channel-analysis/promote-action/mine/detail",
      },
      {
        path: "apply-action",
        meta: {
          icon: "ios-stats",
          title: "申请行为分析",
          sidehead: "申请行为分析-后台管理系统",
          access: ["/analysis/apply"],
          notCache: false,
        },
        name: "channel_apply_action",
        component: "view/channel-analysis/apply-action",
      },
      {
        path: "apply-action-detail",
        meta: {
          icon: "md-body",
          title: "申请行为分析-渠道明细",
          sidehead: "渠道明细-申请行为分析-后台管理系统",
          hideInMenu: true,
          notCache: false,
        },
        name: "channel_apply_action_detail",
        component: "view/channel-analysis/apply-action/detail",
      },
      {
        path: "apply-action-credit-detail",
        meta: {
          icon: "md-body",
          title: "申请行为分析-本地贷渠道明细",
          sidehead: "本地贷渠道明细-申请行为分析-后台管理系统",
          hideInMenu: true,
          notCache: false,
        },
        name: "channel_apply_action_credit_detail",
        component: "view/channel-analysis/apply-action/detail/credit-detail",
      },
      {
        path: "apply-action-mine",
        meta: {
          icon: "ios-stats-outline",
          title: "我的申请行为分析",
          sidehead: "我的申请行为分析-后台管理系统",
          access: ["/analysis/mapply"],
          notCache: false,
        },
        name: "channel_apply_action_mine",
        component: "view/channel-analysis/apply-action/mine",
      },
      {
        path: "apply-action-mine-detail",
        meta: {
          icon: "md-body",
          title: "我的申请行为分析-渠道明细",
          sidehead: "渠道明细-我的申请行为分析-后台管理系统",
          hideInMenu: true,
          notCache: false,
        },
        name: "channel_apply_action_mine_detail",
        component: "view/channel-analysis/apply-action/mine/detail",
      },
      {
        path: "apply-action-mine-credit-detail",
        meta: {
          icon: "md-body",
          title: "我的申请行为分析-本地贷渠道明细",
          sidehead: "本地贷渠道明细-我的申请行为分析-后台管理系统",
          hideInMenu: true,
          notCache: false,
        },
        name: "channel_apply_action_mine_credit_detail",
        component: "view/channel-analysis/apply-action/mine/detail/credit-detail",
      },
      {
        path: "cost-benefit",
        meta: { icon: "ios-calculator", title: "成本收益分析", sidehead: "成本收益分析-后台管理系统", access: ["/analysis/cost"] },
        name: "channel_cost_benefit",
        component: "view/channel-analysis/cost-benefit",
      },
      {
        path: "cost-benefit-detail",
        meta: { icon: "md-body", title: "成本收益分析-渠道明细", sidehead: "渠道明细-成本收益分析-后台管理系统", hideInMenu: true },
        name: "channel_cost_benefit_detail",
        component: "view/channel-analysis/cost-benefit/detail",
      },
      {
        path: "cost-benefit-mine",
        meta: {
          icon: "ios-calculator-outline",
          title: "我的成本收益分析",
          sidehead: "我的成本收益分析-后台管理系统",
          access: ["/analysis/mcost"],
        },
        name: "channel_cost_benefit_mine",
        component: "view/channel-analysis/cost-benefit/mine",
      },
      {
        path: "cost-benefit-mine-detail",
        meta: { icon: "md-body", title: "我的成本收益分析-渠道明细", sidehead: "渠道明细-我的成本收益分析-后台管理系统", hideInMenu: true },
        name: "channel_cost_benefit_mine_detail",
        component: "view/channel-analysis/cost-benefit/mine/detail",
      },
      {
        path: "user-quality",
        meta: { icon: "ios-contacts", title: "用户质量分析", sidehead: "用户质量分析-后台管理系统", access: ["/analysis/quality"] },
        name: "channel_user_quality",
        component: "view/channel-analysis/user-quality",
      },
      {
        path: "user-quality-mine",
        meta: {
          icon: "ios-contacts-outline",
          title: "我的用户质量分析",
          sidehead: "我的用户质量分析-后台管理系统",
          access: ["/analysis/mquality"],
        },
        name: "channel_user_quality_mine",
        component: "view/channel-analysis/user-quality/mine",
      },
      {
        path: "user-keep",
        meta: { icon: "ios-bonfire", title: "用户留存分析", sidehead: "用户留存分析-后台管理系统", access: ["/analysis/keep"] },
        name: "channel_user_keep",
        component: "view/channel-analysis/user-keep",
      },
      {
        path: "user-keep-mine",
        meta: {
          icon: "ios-bonfire-outline",
          title: "我的用户留存分析",
          sidehead: "我的用户留存分析-后台管理系统",
          access: ["/analysis/mkeep"],
        },
        name: "channel_user_keep_mine",
        component: "view/channel-analysis/user-keep/mine",
      },
      {
        path: "portrayal",
        meta: {
          icon: "ios-people",
          title: "用户画像分析",
          sidehead: "用户画像分析-后台管理系统",
          access: ["/analysis/portrait"],
          keepAlive: true,
        },
        name: "portrayal",
        component: "view/channel-analysis/portrayal",
      },
      {
        path: "user-portrait-mine-new",
        meta: {
          icon: "ios-people-outline",
          title: "我的用户画像分析",
          sidehead: "我的用户画像分析-后台管理系统",
          access: ["/analysis/new/mportrait"],
          keepAlive: true,
        },
        name: "channel_user_portrait_mine_new",
        component: "view/channel-analysis/portrayal/new_index",
      },
      {
        path: "user-portrait-mine",
        meta: {
          icon: "ios-people-outline",
          title: "我的用户画像分析(老版",
          sidehead: "我的用户画像分析-后台管理系统",
          access: ["/analysis/mportrait"],
        },
        name: "channel_user_portrait_mine",
        component: "view/channel-analysis/user-portrait/mine",
      },
      {
        path: "channel-transform-analysis",
        meta: {
          icon: "ios-people-outline",
          title: "渠道转化分析",
          sidehead: "渠道转化分析-后台管理系统",
          access: ["/analysis/channel-transform-analysis"],
          keepAlive: true,
        },
        name: "channel-transform-analysis",
        component: "view/channel-analysis/channel-transform-analysis",
      },
      {
        path: "channel-transform-analysis-mine",
        meta: {
          icon: "ios-people-outline",
          title: "我的渠道转化分析",
          sidehead: "渠道转化分析-后台管理系统",
          access: ["/analysis/channel-transform-analysis-mine"],
          keepAlive: true,
        },
        name: "channel-transform-analysis-mine",
        component: "view/channel-analysis/channel-transform-analysis/new.vue",
      },
      {
        path: "user-portrait-area",
        meta: {
          icon: "ios-people-outline",
          title: "区域分布情况",
          sidehead: "区域用户画像分析-后台管理系统",
          hideInMenu: true,
          access: ["/analysis/portrait"],
        },
        name: "channel_user_portrait_area",
        component: "view/channel-analysis/user-portrait/detail-area",
      },
      {
        path: "my-user-portrait-area",
        meta: {
          icon: "ios-people-outline",
          title: "区域分布情况",
          sidehead: "我的区域用户画像分析-后台管理系统",
          hideInMenu: true,
          access: ["/analysis/portrait"],
        },
        name: "channel_my_user_portrait_area",
      },
      {
        path: "user-portrait-house",
        meta: {
          icon: "ios-people-outline",
          title: "房产详情",
          sidehead: "用户画像房产分析-后台管理系统",
          hideInMenu: true,
          access: ["/analysis/portrait"],
        },
        name: "channel_user_portrait_house",
        component: "view/channel-analysis/user-portrait/detail-house",
      },
      {
        path: "my-user-portrait-house",
        meta: {
          icon: "ios-people-outline",
          title: "房产详情",
          sidehead: "我的用户画像房产分析-后台管理系统",
          hideInMenu: true,
          access: ["/analysis/portrait"],
        },
        name: "channel_my_user_portrait_house",
      },
      {
        path: "user-portrait-car",
        meta: {
          icon: "ios-people-outline",
          title: "车产详情",
          sidehead: "用户画像车产分析-后台管理系统",
          hideInMenu: true,
          access: ["/analysis/portrait"],
        },
        name: "channel_user_portrait_car",
        component: "view/channel-analysis/user-portrait/detail-car",
      },
      {
        path: "my-user-portrait-car",
        meta: {
          icon: "ios-people-outline",
          title: "车产详情",
          sidehead: "我的用户画像车产分析-后台管理系统",
          hideInMenu: true,
          access: ["/analysis/portrait"],
        },
        name: "channel_my_user_portrait_car",
      },
      {
        path: "user-portrait-insurance",
        meta: {
          icon: "ios-people-outline",
          title: "寿险保单详情",
          sidehead: "用户画像寿险保单分析-后台管理系统",
          hideInMenu: true,
          access: ["/analysis/portrait"],
        },
        name: "channel_user_portrait_insurance",
        component: "view/channel-analysis/user-portrait/detail-insurance",
      },
      {
        path: "my-user-portrait-insurance",
        meta: {
          icon: "ios-people-outline",
          title: "寿险保单详情",
          sidehead: "我的用户画像寿险保单分析-后台管理系统",
          hideInMenu: true,
          access: ["/analysis/portrait"],
        },
        name: "channel_my_user_portrait_insurance",
      },
      {
        path: "user-portrait-creditcard",
        meta: {
          icon: "ios-people-outline",
          title: "信用卡详情",
          sidehead: "用户画像信用卡分析-后台管理系统",
          hideInMenu: true,
          access: ["/analysis/portrait"],
        },
        name: "channel_user_portrait_creditcard",
        component: "view/channel-analysis/user-portrait/detail-creditcard",
      },
      {
        path: "my-user-portrait-creditcard",
        meta: {
          icon: "ios-people-outline",
          title: "信用卡详情",
          sidehead: "我的用户画像信用卡分析-后台管理系统",
          hideInMenu: true,
          access: ["/analysis/portrait"],
        },
        name: "channel_my_user_portrait_creditcard",
      },
      {
        path: "access-referer",
        meta: { icon: "ios-analytics", title: "访问来源分析", sidehead: "访问来源分析-后台管理系统", access: ["/analysis/access"] },
        name: "channel_access_referer",
        component: "view/channel-analysis/access-referer",
      },
      {
        path: "access-referer-mine",
        meta: {
          icon: "ios-analytics-outline",
          title: "我的访问来源分析",
          sidehead: "我的访问来源分析-后台管理系统",
          access: ["/analysis/maccess"],
        },
        name: "channel_access_referer_mine",
        component: "view/channel-analysis/access-referer/mine",
      },
      {
        path: "user-behavior-data",
        meta: {
          icon: "ios-analytics-outline",
          title: "用户行为数据",
          sidehead: "用户行为数据-后台管理系统",
          access: ["49cbc334-4af6-4c37-ac54-ba754d2c699d"],
          keepAlive: true,
        },
        name: "user-behavior-data",
        component: "view/channel-analysis/user-behavior-data",
      },
    ],
  },
  // 商家管理
  {
    path: "/merchants-manage",
    name: "merchants_manage",
    component: 'Main',
    meta: {
      title: "商家管理",
      icon: "ios-happy-outline",
      access: ["/merchants-manage"],
    },
    children: [
      {
        path: "merchants-list",
        name: "merchants_list",
        meta: {
          icon: "md-list",
          title: "商家列表",
          sidehead: "商家列表-后台管理系统",
          access: ["view/merchants/merchants-list-new.html"],
          keepAlive: true,
        },
        component: "view/merchants/list",
      },
      {
        path: "/merchants/edit",
        name: "merchants_edit",
        meta: {
          icon: "ios-browsers",
          title: "商家编辑",
          sidehead: "商家编辑-商家列表-后台管理系统",
          hideInMenu: true,
        },
        component: "view/merchants/list/merchants-edit",
      },
      {
        path: "/merchants/detail",
        name: "merchants_detail",
        meta: {
          icon: "ios-browsers",
          title: "商家详情",
          sidehead: "商家详情-商家列表-后台管理系统",
          /*access: ['/system/application']*/
          hideInMenu: true,
        },
        component: "view/merchants/list/merchants-detail",
      },
    ],
  },

  // 结算管理
  {
    path: "/settlement-manage",
    name: "settlement_manager",
    component: 'Main',
    meta: {
      title: "结算管理",
      icon: "ios-happy-outline",
      access: ["/settlement-manage"],
    },
    children: [
      {
        path: "settlement-account-list",
        name: "settlement_account_list",
        meta: {
          icon: "md-list",
          title: "结算账户管理",
          sidehead: "结算账户管理-结算管理-后台管理系统",
          access: ["view/settlement/account-list.html"],
        },
        component: "view/settlement/account",
      },
      {
        path: "settlement-income-list",
        name: "settlement_income_list",
        meta: {
          icon: "md-list",
          title: "收入结算",
          sidehead: "收入结算-结算管理-后台管理系统",
          access: ["view/settlement/management-list.html"],
          keepAlive: true,
        },
        component: "view/settlement/income",
      },
      {
        path: "settlement-payment-list",
        name: "settlement_payment_list",
        meta: {
          icon: "md-list",
          title: "支出结算",
          sidehead: "支出结算-结算管理-后台管理系统",
          access: ["view/settlement/payment-settlement.html"],
          keepAlive: true,
        },
        component: "view/settlement/payment",
      },
      {
        path: "settlement-account-edit",
        name: "settlement_account_edit",
        meta: { icon: "md-list", title: "结算账户编辑", sidehead: "结算账户编辑-结算管理-后台管理系统", access: [], hideInMenu: true },
        component: "view/settlement/account/edit",
      },
      {
        path: "settlement-income-detail",
        name: "settlement_income_detail",
        meta: { icon: "md-list", title: "收入结算详情", sidehead: "收入结算详情-收入结算-结算管理-后台管理系统", access: [], hideInMenu: true },
        component: "view/settlement/income/detail",
      },
      {
        path: "settlement-payment-detail",
        name: "settlement_payment_detail",
        meta: { icon: "md-list", title: "支出结算详情", sidehead: "支出结算详情-支出结算-结算管理-后台管理系统", access: [], hideInMenu: true },
        component: "view/settlement/payment/detail",
      },
    ],
  },
  //订单管理
  {
    path: "/order-manage",
    name: "order_manage",
    component: 'Main',
    meta: {
      title: "订单管理",
      icon: "ios-star",
      access: ["/xindaiorder"],
    },
    children: [
      {
        path: "match",
        meta: { icon: "md-people", title: "助贷匹配信息", keepAlive: true, sidehead: "助贷匹配信息-后台管理系统", access: ["order-manage/match"] },
        name: "xd_order_match",
        component: "view/order-manage/match",
      },

      {
        path: "list",
        meta: { icon: "md-people", title: "助贷申请订单", sidehead: "助贷申请订单-后台管理系统", access: ["/xindai/order-manage"] },
        name: "xd_order_list_",
        component: "view/order-manage/list",
      },
      // 退单记录
      {
        path: "/order-manage/chargebackRecord",
        meta: {
          icon: "md-people",
          title: "退单记录",
          sidehead: "三方同业订单管理-后台管理系统",
          access: ["chargebackRecord"],
          keepAlive: true,
        },
        name: "chargebackRecord",
        component: "view/order-manage/chargebackRecord",
      },
      {
        path: "apply",
        meta: { icon: "md-people", title: "极速贷申请订单", keepAlive: true, sidehead: "极速贷申请订单-后台管理系统", access: ["/speed/loan/apply"] }, // '/speedLoan/apply'
        name: "speed_loan_apply",
        component: "view/order-manage/apply",
      },
      {
        path: "loan",
        meta: { icon: "md-people", title: "极速贷贷款订单", keepAlive: true, sidehead: "极速贷贷款订单-后台管理系统", access: ["/speed/loan/order"] }, // '/speedLoan/order'
        name: "speed_loan_order",
        component: "view/order-manage/loan",
      },

      {
        path: "user",
        meta: { icon: "md-people", title: "用户申请列表", keepAlive: true, sidehead: "用户申请列表-后台管理系统", access: ["/xindai/user-manage"] }, // '/speedLoan/order'
        name: "xd_user",
        component: "view/order-manage/user",
      },
      {
        path: "user/detail",
        meta: { icon: "md-people", title: "用户详情", sidehead: "用户详情-后台管理系统", hideInMenu: true }, // '/speedLoan/order'
        name: "xd_user_detail",
        component: "view/order-manage/user/detail",
      },
      {
        path: "product-recommend",
        meta: {
          icon: "md-people",
          title: "产品推荐服务订单",
          sidehead: "产品推荐服务订单-后台管理系统",
          access: ["/serveProductOrder/orderList/{serveCode}"],
          keepAlive: true,
        },
        name: "product_recommend_order",
        component: "view/order-manage/product-recommend",
      },
      // 三方同业订单管理 Tripartite order management
      {
        path: "/order-manage/tripartiteOrder",
        meta: {
          icon: "md-people",
          title: "三方同业订单",
          sidehead: "三方同业订单管理-后台管理系统",
          access: ["tripartiteOrder"],
          keepAlive: true,
        },
        name: "tripartiteOrder",
        component: "view/order-manage/tripartiteOrder",
      },
      {
        path: "/order-manage/tripartiteOrder/detail",
        meta: {
          icon: "md-people",
          title: "银行贷款订单详情",
          sidehead: "银行贷款订单详情-后台管理系统",
          access: ["tripartiteOrder/detail"],
        },
        name: "tripartiteOrderDetail",
        component: "view/order-manage/tripartiteOrder/detail",
      },
    ],
  },
  //金币管理
  {
    path: "/coin-manage",
    name: "coin_manage",
    component: 'Main',
    meta: {
      title: "金币管理",
      icon: "ios-happy-outline",
      access: ["/coin/manage"],
    },
    children: [
      {
        path: "task-manage",
        meta: { icon: "md-list", title: "任务管理", keepAlive: true, sidehead: "任务管理-后台管理系统", access: ["/task/manage"] },
        name: "coin_task_manage",
        component: "view/coin-manage/task-manage",
      },
      {
        path: "gold-rule",
        meta: { icon: "ios-paper", title: "金币规则", sidehead: "金币规则-后台管理系统", access: ["/coin/rule"] },
        name: "coin_gold_rule",
        component: "view/coin-manage/gold-rule",
      },
    ],
  },
  //自助工具
  {
    path: "/help-tool",
    name: "help_tool",
    component: 'Main',
    meta: {
      title: "自助工具",
      icon: "ios-star",
      access: ["/help/tool"],
    },
    children: [
      {
        path: "list",
        meta: { icon: "md-people", title: "渠道数据录入", keepAlive: true, sidehead: "渠道数据录入-后台管理系统", access: ["/tool/tool"] },
        name: "tool_list",
        component: "view/help-tool/list",
      },
      {
        path: "linkconvert",
        meta: { icon: "md-people", title: "内链转换", sidehead: "内链转换-后台管理系统", access: ["/tool/linkconvert"] },
        name: "link_convert",
        component: "view/help-tool/linkconvert",
      },
      {
        path: "link-statistics",
        meta: { icon: "ios-stats", title: "链接数据统计", keepAlive: true, sidehead: "链接数据统计-后台管理系统", access: ["/tool/link-statistics"] },
        name: "link_statistics",
        component: "view/help-tool/link-statistics",
      },
      {
        path: "apply-information",
        meta: { icon: "md-search", title: "申请信息查询", sidehead: "申请信息查询-后台管理系统", access: ["/tool/apply-information"] },
        name: "apply_information",
        component: "view/help-tool/apply-information",
      },
      {
        path: "fileUpload",
        meta: { icon: "md-people", title: "文件上传", sidehead: "文件上传-后台管理系统" },
        name: "link_fileUpload",
        component: "view/help-tool/fileUpload",
      },

      {
        path: "xdProductApply",
        meta: { icon: "md-people", title: "手推银行贷", sidehead: "内链转换-后台管理系统", access: ["/tool/xdproductapply"] },
        name: "xd_product_apply",
        component: "view/help-tool/xdproductapply",
      },
      {
        path: "phoneEncryption",
        meta: {
          icon: "md-people",
          title: "数据加解密",
          sidehead: "数据加解密-后台管理系统",
          access: ["/tool/phoneEncryption"],
          keepAlive: true,
        },
        name: "phone_encryption",
        component: "view/help-tool/phoneEncryption",
      },
      // 渠道来源查询
      {
        path: "channelSourceQuery",
        meta: {
          icon: "md-people",
          title: "渠道来源查询",
          sidehead: "渠道来源查询-后台管理系统",
          access: ["/tool/channelSourceQuery"],
          keepAlive: true,
        },
        name: "channel_source_query",
        component: "view/help-tool/channelSourceQuery",
      },
      {
        path: "carNo",
        meta: {
          icon: "md-people",
          title: "车牌信息查询",
          sidehead: "车牌信息查询-后台管理系统",
          access: ["09204a74-e2ee-47a9-91c5-abb139a5c048"],
          keepAlive: true,
        },
        name: "carNo",
        component: "view/help-tool/carNoInfo",
      },
      {
        path: "userFormInfo",
        meta: {
          icon: "md-people",
          title: "用户表单信息查询",
          sidehead: "用户表单信息查询-后台管理系统",
          access: ["10546264-8088-4a87-a41d-059a140102bc"],
          keepAlive: true,
        },
        name: "userFormInfo",
        component: "view/help-tool/userFormInfo",
      },
      // 虚拟手机号
      {
        path: "random-mobile",
        meta: {
          icon: "md-phone-portrait",
          title: "随机手机号",
          sidehead: "随机手机号-后台管理系统",
          access: ["423d9c55-5916-4696-9424-5fdc46c8fa4f"],
          keepAlive: true,
        },
        name: "RandomMobile",
        component: "view/help-tool/random-mobile/index.vue",
      },
      {
        path: "docking-json",
        meta: {
          icon: "md-list-box",
          title: "对接参数构建",
          sidehead: "对接参数构建-后台管理系统",
          keepAlive: true,
          access: [],
        },
        name: "DockingJson",
        component: "view/help-tool/docking-json/index.vue",
      },
      {
        path: "param_builder",
        meta: {
          icon: "md-list-box",
          title: "助贷API配置与测试",
          sidehead: "助贷API配置与测试-后台管理系统",
          access: [],
        },
        name: "ParamBuilder",
        component: "view/help-tool/param-builder/index.vue",
      },
    ],
  },
  //平台数据统计
  {
    path: "/data-statistics",
    name: "data-statistics",
    component: 'Main',
    meta: {
      title: "平台数据统计",
      icon: "ios-cog",
      access: ["/data-statistics"],
      hideInMenu: true,
    },
    children: [],
  },
  //消息管理
  {
    path: "/message",
    name: "message",
    component: 'Main',
    meta: {
      title: "消息管理",
      icon: "ios-chatboxes",
      access: ["/message"],
    },
    children: [
      {
        path: "/message/manager",
        meta: { icon: "ios-pricetag", title: "消息列表", keepAlive: true, sidehead: "消息列表-后台管理系统", access: ["/message/list"] },
        name: "message_manager",
        component: "view/message/manager",
      },
      {
        path: "/message/manager/messageDetail",
        meta: { title: "消息详情", sidehead: "消息详情-消息管理-后台管理系统", hideInMenu: true },
        name: "message_messageDetail",
        component: "view/message/manager/messageDetail",
      },
      {
        path: "sms/promote",
        name: "sms_promote",
        meta: { icon: "ios-chatbubbles-outline", title: "召回短信列表", keepAlive: true, sidehead: "召回短信列表-后台管理系统", access: ["/message/sms/promote"] },
        component: "view/message/sms-promote",
      },
    ],
  },
  //黑白名单管理
  {
    path: "/blackwhitelistmanage",
    name: "blackwhitelistmanage",
    component: 'Main',
    meta: {
      title: "黑白名单管理",
      icon: "ios-chatboxes",
      access: ["5ea992ed-05bb-4cac-a7b8-59cbb15ebdc8"],
    },
    children: [
      {
        path: "/blackwhitelistmanage/phoneblack",
        meta: {
          icon: "ios-pricetag",
          title: "手机号段黑名单",
          sidehead: "手机号段黑名单-后台管理系统",
          access: ["99988e2d-df63-420a-8112-cfab7bdc140b"],
          keepAlive: true,
        },
        name: "phoneblack",
        component: "view/blackwhitelistmanage/phoneblack",
      },
      {
        path: "/blackwhitelistmanage/ipblack",
        meta: { icon: "ios-pricetag", title: "IP黑名单", keepAlive: true, sidehead: "IP黑名单-后台管理系统", access: ["bf529519-7987-40eb-967f-2b8028614a00"] },
        name: "ipblack",
        component: "view/blackwhitelistmanage/ipblack",
      },
      {
        path: "/blackwhitelistmanage/ipwhite",
        meta: { icon: "ios-pricetag", title: "IP白名单", keepAlive: true, sidehead: "IP白名单-后台管理系统", access: ["fee40db0-8f39-4fce-8179-1c9bd1b1a52a"] },
        name: "ipwhite",
        component: "view/blackwhitelistmanage/ipwhite",
      },
    ],
  },
  //媒体投放
  {
    path: "/media-delivery",
    name: "media-delivery",
    component: 'Main',
    meta: {
      title: "媒体投放",
      icon: "ios-chatboxes",
      access: ["4c6dec19-5ce3-49f8-af40-555c88a875cd"],
    },
    children: [
      {
        path: "/media-delivery/return-rule-config",
        name: "return-rule-config",
        meta: {
          icon: "ios-pricetag",
          title: "回传规则配置",
          sidehead: "回传规则配置-后台管理系统",
          access: ["d6e8e98e-8f59-4656-8262-852c4aee8092"],
          keepAlive: true,
        },
        component: "view/media-delivery/return-rule-config",
      },
      {
        path: "/media-delivery/user-return-plan",
        name: "user-return-plan",
        meta: {
          icon: "ios-pricetag",
          title: "用户回传计划",
          sidehead: "用户回传计划-后台管理系统",
          access: ["4983fa24-5205-49d2-bdf1-b8615d7cb9f4"],
          keepAlive: true,
        },
        component: "view/media-delivery/user-return-plan",
      },
      {
        path: "return-plan-detail",
        name: "return-plan-detail",
        meta: {
          icon: "ios-pricetag",
          title: "新增/编辑计划",
          sidehead: "用户回传计划-后台管理系统",
          access: ["/media-delivery/user-return-plan/detail"],
        },
        component: "view/media-delivery/user-return-plan/detail.vue",
      },
      {
        path: "/media-delivery/user-query",
        name: "user-query",
        meta: {
          icon: "md-paper-plane",
          title: "用户查询",
          sidehead: "用户查询-后台管理系统",
          access: ["c8a010ea-c018-4fe7-b537-8fb020e5d567"],
          keepAlive: true,
        },
        component: "view/media-delivery/user-query",
      },
    ],
  },

]